<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (RATION?,MENU?,ITEMTYPE?,ITEM?,WEIGHT?,CALORIES?,TOTALFAT_G?,TOTALFAT_DV?,SATURATEDFAT_G?,SATURATEDFAT_DV?,TRANSFAT_G?,CHOLESTEROL_MG?,CHOLESTEROL_DV?,SODIUM_MG?,SODIUM_DV?,POTASSIUM_MG?,CARBOHYDRATES_G?,CARBOHYDRATES_DV?,DIETARYFIBER_G?,DIETARYFIBER_DV?,SUGARS_G?,PROTEIN_G?,VITAMINA_IU?,VITAMINA_DV?,VITAMINC_MG?,VITAMINC_DV?,CALCIUM_MG?,CALCIUM_DV?,IRON_MG?,IRON_DV?,VITAMIND_MCG?,VITAMINE_MG?,VITAMINK_MCG?,THIAMIN_MG?,RIBOFLAVIN_MG?,NIACIN_MG?,VITAMINB6_MG?,FOLICACID_MCG?,VITAMINB12_MCG?,PHOSPHOROUS_MG?,IODINE_MCG?,MAGNESIUM_MG?,ZINC_MG?,SELENIUM_MCG?)+>
  <!ELEMENT RATION (#PCDATA)>
  <!ELEMENT MENU (#PCDATA)>
  <!ELEMENT ITEMTYPE (#PCDATA)>
  <!ELEMENT ITEM (#PCDATA)>
  <!ELEMENT WEIGHT (#PCDATA)>
  <!ELEMENT CALORIES (#PCDATA)>
  <!ELEMENT TOTALFAT_G (#PCDATA)>
  <!ELEMENT TOTALFAT_DV (#PCDATA)>
  <!ELEMENT SATURATEDFAT_G (#PCDATA)>
  <!ELEMENT SATURATEDFAT_DV (#PCDATA)>
  <!ELEMENT TRANSFAT_G (#PCDATA)>
  <!ELEMENT CHOLESTEROL_MG (#PCDATA)>
  <!ELEMENT CHOLESTEROL_DV (#PCDATA)>
  <!ELEMENT SODIUM_MG (#PCDATA)>
  <!ELEMENT SODIUM_DV (#PCDATA)>
  <!ELEMENT POTASSIUM_MG (#PCDATA)>
  <!ELEMENT CARBOHYDRATES_G (#PCDATA)>
  <!ELEMENT CARBOHYDRATES_DV (#PCDATA)>
  <!ELEMENT DIETARYFIBER_G (#PCDATA)>
  <!ELEMENT DIETARYFIBER_DV (#PCDATA)>
  <!ELEMENT SUGARS_G (#PCDATA)>
  <!ELEMENT PROTEIN_G (#PCDATA)>
  <!ELEMENT VITAMINA_IU (#PCDATA)>
  <!ELEMENT VITAMINA_DV (#PCDATA)>
  <!ELEMENT VITAMINC_MG (#PCDATA)>
  <!ELEMENT VITAMINC_DV (#PCDATA)>
  <!ELEMENT CALCIUM_MG (#PCDATA)>
  <!ELEMENT CALCIUM_DV (#PCDATA)>
  <!ELEMENT IRON_MG (#PCDATA)>
  <!ELEMENT IRON_DV (#PCDATA)>
  <!ELEMENT VITAMIND_MCG (#PCDATA)>
  <!ELEMENT VITAMINE_MG (#PCDATA)>
  <!ELEMENT VITAMINK_MCG (#PCDATA)>
  <!ELEMENT THIAMIN_MG (#PCDATA)>
  <!ELEMENT RIBOFLAVIN_MG (#PCDATA)>
  <!ELEMENT NIACIN_MG (#PCDATA)>
  <!ELEMENT VITAMINB6_MG (#PCDATA)>
  <!ELEMENT FOLICACID_MCG (#PCDATA)>
  <!ELEMENT VITAMINB12_MCG (#PCDATA)>
  <!ELEMENT PHOSPHOROUS_MG (#PCDATA)>
  <!ELEMENT IODINE_MCG (#PCDATA)>
  <!ELEMENT MAGNESIUM_MG (#PCDATA)>
  <!ELEMENT ZINC_MG (#PCDATA)>
  <!ELEMENT SELENIUM_MCG (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Entree</ITEMTYPE>
    <ITEM>Chicken, Spicy Oriental with Rice, Freeze Dried</ITEM>
    <WEIGHT>150</WEIGHT>
    <CALORIES>592.5</CALORIES>
    <TOTALFAT_G>9.15</TOTALFAT_G>
    <TOTALFAT_DV>.14&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>2.52</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.13&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.05</TRANSFAT_G>
    <CHOLESTEROL_MG>54.75</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.18&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>2595</SODIUM_MG>
    <SODIUM_DV>1.08&#37;</SODIUM_DV>
    <POTASSIUM_MG>1194</POTASSIUM_MG>
    <CARBOHYDRATES_G>97.8</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.33&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>6.71</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.27&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>32.25</PROTEIN_G>
    <VITAMINA_IU>435</VITAMINA_IU>
    <VITAMINA_DV>.09&#37;</VITAMINA_DV>
    <VITAMINC_MG>15.6</VITAMINC_MG>
    <VITAMINC_DV>.26&#37;</VITAMINC_DV>
    <CALCIUM_MG>76.5</CALCIUM_MG>
    <CALCIUM_DV>.08&#37;</CALCIUM_DV>
    <IRON_MG>6.45</IRON_MG>
    <IRON_DV>.36&#37;</IRON_DV>
    <VITAMINE_MG>1.39</VITAMINE_MG>
    <VITAMINK_MCG>10.37</VITAMINK_MCG>
    <THIAMIN_MG>.92</THIAMIN_MG>
    <RIBOFLAVIN_MG>1.22</RIBOFLAVIN_MG>
    <NIACIN_MG>17.25</NIACIN_MG>
    <VITAMINB6_MG>1.28</VITAMINB6_MG>
    <FOLICACID_MCG>286.5</FOLICACID_MCG>
    <VITAMINB12_MCG>.63</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>499.5</PHOSPHOROUS_MG>
    <IODINE_MCG>104.85</IODINE_MCG>
    <MAGNESIUM_MG>102.9</MAGNESIUM_MG>
    <ZINC_MG>3.98</ZINC_MG>
    <SELENIUM_MCG>36</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Ice Cream Sandwich, Freeze Dried</ITEM>
    <WEIGHT>28</WEIGHT>
    <CALORIES>133</CALORIES>
    <TOTALFAT_G>5.16</TOTALFAT_G>
    <TOTALFAT_DV>.08&#37;</TOTALFAT_DV>
    <TRANSFAT_G>.34</TRANSFAT_G>
    <CHOLESTEROL_MG>14.24</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.05&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>133</SODIUM_MG>
    <SODIUM_DV>.06&#37;</SODIUM_DV>
    <CARBOHYDRATES_G>19.17</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.06&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.9</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.04&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>2.64</PROTEIN_G>
    <VITAMINA_IU>10</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <CALCIUM_MG>40.01</CALCIUM_MG>
    <CALCIUM_DV>.04&#37;</CALCIUM_DV>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Fig Bar</ITEM>
    <WEIGHT>54.8</WEIGHT>
    <CALORIES>195.09</CALORIES>
    <TOTALFAT_G>3.47</TOTALFAT_G>
    <TOTALFAT_DV>.05&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>.75</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.04&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.83</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>210.98</SODIUM_MG>
    <SODIUM_DV>.09&#37;</SODIUM_DV>
    <POTASSIUM_MG>93.71</POTASSIUM_MG>
    <CARBOHYDRATES_G>39.51</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.13&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.03</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.04&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>2.08</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.55</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>21.54</CALCIUM_MG>
    <CALCIUM_DV>.02&#37;</CALCIUM_DV>
    <IRON_MG>1.08</IRON_MG>
    <IRON_DV>.06&#37;</IRON_DV>
    <VITAMINE_MG>.44</VITAMINE_MG>
    <THIAMIN_MG>.05</THIAMIN_MG>
    <RIBOFLAVIN_MG>.09</RIBOFLAVIN_MG>
    <NIACIN_MG>.9</NIACIN_MG>
    <VITAMINB6_MG>.02</VITAMINB6_MG>
    <FOLICACID_MCG>7.29</FOLICACID_MCG>
    <VITAMINB12_MCG>.07</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>27.67</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>10.8</MAGNESIUM_MG>
    <ZINC_MG>.19</ZINC_MG>
    <SELENIUM_MCG>1.7</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Dairy Shake</ITEMTYPE>
    <ITEM>Dairyshake Powder, Chocolate, Fortified</ITEM>
    <WEIGHT>100</WEIGHT>
    <CALORIES>452.5</CALORIES>
    <TOTALFAT_G>16.2</TOTALFAT_G>
    <TOTALFAT_DV>.25&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>3.35</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.17&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>5.61</TRANSFAT_G>
    <CHOLESTEROL_MG>5</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.02&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>226</SODIUM_MG>
    <SODIUM_DV>.09&#37;</SODIUM_DV>
    <POTASSIUM_MG>963.5</POTASSIUM_MG>
    <CARBOHYDRATES_G>60.9</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.2&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.93</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.08&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>16.6</PROTEIN_G>
    <VITAMINA_IU>1058.5</VITAMINA_IU>
    <VITAMINA_DV>.21&#37;</VITAMINA_DV>
    <VITAMINC_MG>2.6</VITAMINC_MG>
    <VITAMINC_DV>.04&#37;</VITAMINC_DV>
    <CALCIUM_MG>510.5</CALCIUM_MG>
    <CALCIUM_DV>.51&#37;</CALCIUM_DV>
    <IRON_MG>2.31</IRON_MG>
    <IRON_DV>.13&#37;</IRON_DV>
    <VITAMIND_MCG>8.8</VITAMIND_MCG>
    <VITAMINE_MG>.67</VITAMINE_MG>
    <THIAMIN_MG>.1</THIAMIN_MG>
    <RIBOFLAVIN_MG>.84</RIBOFLAVIN_MG>
    <NIACIN_MG>.65</NIACIN_MG>
    <VITAMINB6_MG>.23</VITAMINB6_MG>
    <FOLICACID_MCG>20.9</FOLICACID_MCG>
    <VITAMINB12_MCG>2</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>507</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>66.8</MAGNESIUM_MG>
    <ZINC_MG>2.01</ZINC_MG>
    <SELENIUM_MCG>14.65</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Dairy Shake</ITEMTYPE>
    <ITEM>Dairyshake Powder, Strawberry Banana, Fortified</ITEM>
    <WEIGHT>100</WEIGHT>
    <CALORIES>451.5</CALORIES>
    <TOTALFAT_G>15.75</TOTALFAT_G>
    <TOTALFAT_DV>.24&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>3.33</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.17&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>5.4</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>244</SODIUM_MG>
    <SODIUM_DV>.1&#37;</SODIUM_DV>
    <POTASSIUM_MG>858.5</POTASSIUM_MG>
    <CARBOHYDRATES_G>60.8</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.2&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>2.7</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.11&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>17.2</PROTEIN_G>
    <VITAMINA_IU>521</VITAMINA_IU>
    <VITAMINA_DV>.1&#37;</VITAMINA_DV>
    <VITAMINC_MG>2.95</VITAMINC_MG>
    <VITAMINC_DV>.05&#37;</VITAMINC_DV>
    <CALCIUM_MG>539.5</CALCIUM_MG>
    <CALCIUM_DV>.54&#37;</CALCIUM_DV>
    <IRON_MG>.3</IRON_MG>
    <IRON_DV>.02&#37;</IRON_DV>
    <VITAMIND_MCG>5.7</VITAMIND_MCG>
    <VITAMINE_MG>.86</VITAMINE_MG>
    <THIAMIN_MG>.13</THIAMIN_MG>
    <RIBOFLAVIN_MG>.87</RIBOFLAVIN_MG>
    <NIACIN_MG>.53</NIACIN_MG>
    <VITAMINB6_MG>.15</VITAMINB6_MG>
    <FOLICACID_MCG>14.35</FOLICACID_MCG>
    <VITAMINB12_MCG>2.32</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>516</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>49</MAGNESIUM_MG>
    <ZINC_MG>2.27</ZINC_MG>
    <SELENIUM_MCG>20.75</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Dairy Shake</ITEMTYPE>
    <ITEM>Dairyshake Powder, Strawberry, Fortified</ITEM>
    <WEIGHT>100</WEIGHT>
    <CALORIES>453.5</CALORIES>
    <TOTALFAT_G>16.3</TOTALFAT_G>
    <TOTALFAT_DV>.25&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>3.18</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.16&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>5.82</TRANSFAT_G>
    <CHOLESTEROL_MG>5</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.02&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>243.5</SODIUM_MG>
    <SODIUM_DV>.1&#37;</SODIUM_DV>
    <POTASSIUM_MG>852.5</POTASSIUM_MG>
    <CARBOHYDRATES_G>60.6</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.2&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.04&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>16.95</PROTEIN_G>
    <VITAMINA_IU>767</VITAMINA_IU>
    <VITAMINA_DV>.15&#37;</VITAMINA_DV>
    <VITAMINC_MG>1.95</VITAMINC_MG>
    <VITAMINC_DV>.03&#37;</VITAMINC_DV>
    <CALCIUM_MG>548.5</CALCIUM_MG>
    <CALCIUM_DV>.55&#37;</CALCIUM_DV>
    <IRON_MG>.27</IRON_MG>
    <IRON_DV>.02&#37;</IRON_DV>
    <VITAMIND_MCG>9.25</VITAMIND_MCG>
    <VITAMINE_MG>.64</VITAMINE_MG>
    <THIAMIN_MG>.1</THIAMIN_MG>
    <RIBOFLAVIN_MG>.86</RIBOFLAVIN_MG>
    <NIACIN_MG>.54</NIACIN_MG>
    <VITAMINB6_MG>.24</VITAMINB6_MG>
    <FOLICACID_MCG>18.55</FOLICACID_MCG>
    <VITAMINB12_MCG>2.24</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>513.5</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>48.4</MAGNESIUM_MG>
    <ZINC_MG>1.79</ZINC_MG>
    <SELENIUM_MCG>16.2</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Dairy Shake</ITEMTYPE>
    <ITEM>Dairyshake Powder, Vanilla, Fortified</ITEM>
    <WEIGHT>100</WEIGHT>
    <CALORIES>464</CALORIES>
    <TOTALFAT_G>18.7</TOTALFAT_G>
    <TOTALFAT_DV>.29&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>2.7</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.14&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>5.15</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>238</SODIUM_MG>
    <SODIUM_DV>.1&#37;</SODIUM_DV>
    <POTASSIUM_MG>912</POTASSIUM_MG>
    <CARBOHYDRATES_G>58.9</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.2&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.04&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>16.7</PROTEIN_G>
    <VITAMINA_IU>764</VITAMINA_IU>
    <VITAMINA_DV>.15&#37;</VITAMINA_DV>
    <VITAMINC_MG>3.2</VITAMINC_MG>
    <VITAMINC_DV>.05&#37;</VITAMINC_DV>
    <CALCIUM_MG>522</CALCIUM_MG>
    <CALCIUM_DV>.52&#37;</CALCIUM_DV>
    <IRON_MG>.26</IRON_MG>
    <IRON_DV>.01&#37;</IRON_DV>
    <VITAMIND_MCG>9.2</VITAMIND_MCG>
    <VITAMINE_MG>.62</VITAMINE_MG>
    <THIAMIN_MG>.08</THIAMIN_MG>
    <RIBOFLAVIN_MG>.84</RIBOFLAVIN_MG>
    <NIACIN_MG>.5</NIACIN_MG>
    <VITAMINB6_MG>.24</VITAMINB6_MG>
    <FOLICACID_MCG>15.3</FOLICACID_MCG>
    <VITAMINB12_MCG>2.36</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>538</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>45.4</MAGNESIUM_MG>
    <ZINC_MG>1.79</ZINC_MG>
    <SELENIUM_MCG>14.8</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Dairy Shake</ITEMTYPE>
    <ITEM>Group Average - MCW/LRP 2008 Dairy Shake</ITEM>
    <WEIGHT>100</WEIGHT>
    <CALORIES>455.38</CALORIES>
    <TOTALFAT_G>16.74</TOTALFAT_G>
    <TOTALFAT_DV>.26&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>3.14</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.16&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>5.5</TRANSFAT_G>
    <CHOLESTEROL_MG>2.5</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.01&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>237.88</SODIUM_MG>
    <SODIUM_DV>.1&#37;</SODIUM_DV>
    <POTASSIUM_MG>896.63</POTASSIUM_MG>
    <CARBOHYDRATES_G>60.3</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.2&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.66</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.07&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>16.86</PROTEIN_G>
    <VITAMINA_IU>777.63</VITAMINA_IU>
    <VITAMINA_DV>.16&#37;</VITAMINA_DV>
    <VITAMINC_MG>2.68</VITAMINC_MG>
    <VITAMINC_DV>.04&#37;</VITAMINC_DV>
    <CALCIUM_MG>530.13</CALCIUM_MG>
    <CALCIUM_DV>.53&#37;</CALCIUM_DV>
    <IRON_MG>.78</IRON_MG>
    <IRON_DV>.04&#37;</IRON_DV>
    <VITAMIND_MCG>8.24</VITAMIND_MCG>
    <VITAMINE_MG>.7</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.1</THIAMIN_MG>
    <RIBOFLAVIN_MG>.85</RIBOFLAVIN_MG>
    <NIACIN_MG>.55</NIACIN_MG>
    <VITAMINB6_MG>.21</VITAMINB6_MG>
    <FOLICACID_MCG>17.28</FOLICACID_MCG>
    <VITAMINB12_MCG>2.23</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>518.63</PHOSPHOROUS_MG>
    <IODINE_MCG>0</IODINE_MCG>
    <MAGNESIUM_MG>52.4</MAGNESIUM_MG>
    <ZINC_MG>1.96</ZINC_MG>
    <SELENIUM_MCG>16.6</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Beverage</ITEMTYPE>
    <ITEM>Beverage Base, Carbohydrate Fortified, Formulation D</ITEM>
    <WEIGHT>34</WEIGHT>
    <CALORIES>130</CALORIES>
    <TOTALFAT_G>0</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>10</SODIUM_MG>
    <SODIUM_DV>0&#37;</SODIUM_DV>
    <CARBOHYDRATES_G>33</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.11&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>0</PROTEIN_G>
    <VITAMINA_DV> </VITAMINA_DV>
    <VITAMINC_MG>45</VITAMINC_MG>
    <VITAMINC_DV>.75&#37;</VITAMINC_DV>
    <CALCIUM_MG>0</CALCIUM_MG>
    <CALCIUM_DV>0&#37;</CALCIUM_DV>
    <VITAMINE_MG>0</VITAMINE_MG>
    <THIAMIN_MG>0</THIAMIN_MG>
    <RIBOFLAVIN_MG>0</RIBOFLAVIN_MG>
    <NIACIN_MG>0</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>0</FOLICACID_MCG>
    <VITAMINB12_MCG>0</VITAMINB12_MCG>
    <MAGNESIUM_MG>0</MAGNESIUM_MG>
    <ZINC_MG>0</ZINC_MG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Accessory Pack</ITEMTYPE>
    <ITEM>Chewing Gum, Xylitol</ITEM>
    <WEIGHT>3.2</WEIGHT>
    <CARBOHYDRATES_G>2</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.01&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Accessory Pack</ITEMTYPE>
    <ITEM>Coffee, Soluble, Freeze Dried</ITEM>
    <WEIGHT>1.7</WEIGHT>
    <CALORIES>5.8</CALORIES>
    <TOTALFAT_G>.01</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>0</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>0</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>2.35</SODIUM_MG>
    <SODIUM_DV>0&#37;</SODIUM_DV>
    <POTASSIUM_MG>57.46</POTASSIUM_MG>
    <CARBOHYDRATES_G>1.09</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>0&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.38</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.02&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.36</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.02</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>3.42</CALCIUM_MG>
    <CALCIUM_DV>0&#37;</CALCIUM_DV>
    <IRON_MG>.05</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
    <VITAMINE_MG>.01</VITAMINE_MG>
    <THIAMIN_MG>0</THIAMIN_MG>
    <RIBOFLAVIN_MG>.01</RIBOFLAVIN_MG>
    <NIACIN_MG>.69</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>.12</FOLICACID_MCG>
    <VITAMINB12_MCG>0</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>5.46</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>6.46</MAGNESIUM_MG>
    <ZINC_MG>.01</ZINC_MG>
    <SELENIUM_MCG>.05</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Accessory Pack</ITEMTYPE>
    <ITEM>Creamer, Non-Dairy, Dry</ITEM>
    <WEIGHT>4</WEIGHT>
    <CALORIES>21</CALORIES>
    <TOTALFAT_G>1.46</TOTALFAT_G>
    <TOTALFAT_DV>.02&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>0</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.5</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>8.5</SODIUM_MG>
    <SODIUM_DV>0&#37;</SODIUM_DV>
    <POTASSIUM_MG>41</POTASSIUM_MG>
    <CARBOHYDRATES_G>2.08</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.01&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>0</DIETARYFIBER_G>
    <DIETARYFIBER_DV>0&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.1</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>0</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>.5</CALCIUM_MG>
    <CALCIUM_DV>0&#37;</CALCIUM_DV>
    <IRON_MG>.02</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
    <VITAMINE_MG>0</VITAMINE_MG>
    <THIAMIN_MG>0</THIAMIN_MG>
    <RIBOFLAVIN_MG>0</RIBOFLAVIN_MG>
    <NIACIN_MG>0</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>0</FOLICACID_MCG>
    <VITAMINB12_MCG>0</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>18</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>0</MAGNESIUM_MG>
    <ZINC_MG>0</ZINC_MG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Accessory Pack</ITEMTYPE>
    <ITEM>Hot Sauce, Extra Hot 4x</ITEM>
    <WEIGHT>4</WEIGHT>
    <CALORIES>0</CALORIES>
    <TOTALFAT_G>.02</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>22.6</SODIUM_MG>
    <SODIUM_DV>.01&#37;</SODIUM_DV>
    <POTASSIUM_MG>4.12</POTASSIUM_MG>
    <CARBOHYDRATES_G>.04</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>0&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.03</PROTEIN_G>
    <VITAMINC_MG>0</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>.6</CALCIUM_MG>
    <CALCIUM_DV>0&#37;</CALCIUM_DV>
    <IRON_MG>.06</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
    <VITAMINE_MG>0</VITAMINE_MG>
    <THIAMIN_MG>0</THIAMIN_MG>
    <RIBOFLAVIN_MG>0</RIBOFLAVIN_MG>
    <NIACIN_MG>.01</NIACIN_MG>
    <VITAMINB6_MG>.01</VITAMINB6_MG>
    <FOLICACID_MCG>0</FOLICACID_MCG>
    <VITAMINB12_MCG>0</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>.68</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>.4</MAGNESIUM_MG>
    <ZINC_MG>0</ZINC_MG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Accessory Pack</ITEMTYPE>
    <ITEM>Sugar</ITEM>
    <WEIGHT>4</WEIGHT>
    <CALORIES>15</CALORIES>
    <TOTALFAT_G>0</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>0</SODIUM_MG>
    <SODIUM_DV>0&#37;</SODIUM_DV>
    <POTASSIUM_MG>0</POTASSIUM_MG>
    <CARBOHYDRATES_G>4</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.01&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>0</PROTEIN_G>
    <VITAMINC_MG>0</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>0</CALCIUM_MG>
    <CALCIUM_DV>0&#37;</CALCIUM_DV>
    <IRON_MG>0</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
    <VITAMINE_MG>0</VITAMINE_MG>
    <THIAMIN_MG>0</THIAMIN_MG>
    <RIBOFLAVIN_MG>0</RIBOFLAVIN_MG>
    <NIACIN_MG>0</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>0</FOLICACID_MCG>
    <PHOSPHOROUS_MG>0</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>0</MAGNESIUM_MG>
    <ZINC_MG>0</ZINC_MG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>MCW/LRP 2008 Accessory Pack</ITEMTYPE>
    <ITEM>Group Average - MCW/LRP 2008 Accessory Pack</ITEM>
    <WEIGHT>3.38</WEIGHT>
    <CALORIES>10.2</CALORIES>
    <TOTALFAT_G>.38</TOTALFAT_G>
    <TOTALFAT_DV>.01&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>0</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.25</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>8.74</SODIUM_MG>
    <SODIUM_DV>0&#37;</SODIUM_DV>
    <POTASSIUM_MG>20.53</POTASSIUM_MG>
    <CARBOHYDRATES_G>1.83</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.01&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.19</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.01&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.1</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>0</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>1</CALCIUM_MG>
    <CALCIUM_DV>0&#37;</CALCIUM_DV>
    <IRON_MG>.03</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
    <VITAMIND_MCG>0</VITAMIND_MCG>
    <VITAMINE_MG>0</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>0</THIAMIN_MG>
    <RIBOFLAVIN_MG>0</RIBOFLAVIN_MG>
    <NIACIN_MG>.23</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>.04</FOLICACID_MCG>
    <VITAMINB12_MCG>0</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>2.05</PHOSPHOROUS_MG>
    <IODINE_MCG>0</IODINE_MCG>
    <MAGNESIUM_MG>2.29</MAGNESIUM_MG>
    <ZINC_MG>0</ZINC_MG>
    <SELENIUM_MCG>.05</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Total</ITEMTYPE>
    <WEIGHT>370.18</WEIGHT>
    <CALORIES>1516.17</CALORIES>
    <TOTALFAT_G>34.9</TOTALFAT_G>
    <TOTALFAT_DV>0</TOTALFAT_DV>
    <SATURATEDFAT_G>6.41</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0</SATURATEDFAT_DV>
    <TRANSFAT_G>6.97</TRANSFAT_G>
    <CHOLESTEROL_MG>71.49</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0</CHOLESTEROL_DV>
    <SODIUM_MG>3195.6</SODIUM_MG>
    <SODIUM_DV>0</SODIUM_DV>
    <POTASSIUM_MG>2204.87</POTASSIUM_MG>
    <CARBOHYDRATES_G>251.61</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>0</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>10.49</DIETARYFIBER_G>
    <DIETARYFIBER_DV>0</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>53.93</PROTEIN_G>
    <VITAMINA_IU>1222.63</VITAMINA_IU>
    <VITAMINA_DV>0</VITAMINA_DV>
    <VITAMINC_MG>63.83</VITAMINC_MG>
    <VITAMINC_DV>0</VITAMINC_DV>
    <CALCIUM_MG>669.18</CALCIUM_MG>
    <CALCIUM_DV>0</CALCIUM_DV>
    <IRON_MG>8.34</IRON_MG>
    <IRON_DV>0</IRON_DV>
    <VITAMIND_MCG>8.24</VITAMIND_MCG>
    <VITAMINE_MG>2.53</VITAMINE_MG>
    <VITAMINK_MCG>10.37</VITAMINK_MCG>
    <THIAMIN_MG>1.07</THIAMIN_MG>
    <RIBOFLAVIN_MG>2.16</RIBOFLAVIN_MG>
    <NIACIN_MG>18.93</NIACIN_MG>
    <VITAMINB6_MG>1.51</VITAMINB6_MG>
    <FOLICACID_MCG>311.11</FOLICACID_MCG>
    <VITAMINB12_MCG>2.93</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>1047.85</PHOSPHOROUS_MG>
    <IODINE_MCG>104.85</IODINE_MCG>
    <MAGNESIUM_MG>168.39</MAGNESIUM_MG>
    <ZINC_MG>6.13</ZINC_MG>
    <SELENIUM_MCG>54.35</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 2</MENU>
    <ITEMTYPE>Entree</ITEMTYPE>
    <ITEM>Beef Stroganoff with Noodles, Freeze Dried</ITEM>
    <WEIGHT>130</WEIGHT>
    <CALORIES>617.5</CALORIES>
    <TOTALFAT_G>28.86</TOTALFAT_G>
    <TOTALFAT_DV>.44&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>10.04</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.5&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.23</TRANSFAT_G>
    <CHOLESTEROL_MG>85.54</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.29&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>1820</SODIUM_MG>
    <SODIUM_DV>.76&#37;</SODIUM_DV>
    <POTASSIUM_MG>560.3</POTASSIUM_MG>
    <CARBOHYDRATES_G>66.69</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.22&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>2.9</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.12&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>28.08</PROTEIN_G>
    <VITAMINA_IU>273</VITAMINA_IU>
    <VITAMINA_DV>.05&#37;</VITAMINA_DV>
    <VITAMINC_MG>1.3</VITAMINC_MG>
    <VITAMINC_DV>.02&#37;</VITAMINC_DV>
    <CALCIUM_MG>144.3</CALCIUM_MG>
    <CALCIUM_DV>.14&#37;</CALCIUM_DV>
    <IRON_MG>2.33</IRON_MG>
    <IRON_DV>.13&#37;</IRON_DV>
    <VITAMINE_MG>1.38</VITAMINE_MG>
    <THIAMIN_MG>.16</THIAMIN_MG>
    <RIBOFLAVIN_MG>.53</RIBOFLAVIN_MG>
    <NIACIN_MG>4.82</NIACIN_MG>
    <VITAMINB6_MG>.41</VITAMINB6_MG>
    <FOLICACID_MCG>20.54</FOLICACID_MCG>
    <VITAMINB12_MCG>1.9</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>326.3</PHOSPHOROUS_MG>
    <IODINE_MCG>26.13</IODINE_MCG>
    <MAGNESIUM_MG>51.22</MAGNESIUM_MG>
    <ZINC_MG>4.02</ZINC_MG>
    <SELENIUM_MCG>32.11</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 2</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Chocolate Sports Bar</ITEM>
    <WEIGHT>54</WEIGHT>
    <CALORIES>212.64</CALORIES>
    <TOTALFAT_G>4.15</TOTALFAT_G>
    <TOTALFAT_DV>.06&#37;</TOTALFAT_DV>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>105.89</SODIUM_MG>
    <SODIUM_DV>.04&#37;</SODIUM_DV>
    <POTASSIUM_MG>252.56</POTASSIUM_MG>
    <CARBOHYDRATES_G>34.8</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.12&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>9.01</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>0</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>123.44</CALCIUM_MG>
    <CALCIUM_DV>.12&#37;</CALCIUM_DV>
    <IRON_MG>2.5</IRON_MG>
    <IRON_DV>.14&#37;</IRON_DV>
    <VITAMIND_MCG>0</VITAMIND_MCG>
    <VITAMINE_MG>.37</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.04</THIAMIN_MG>
    <RIBOFLAVIN_MG>.27</RIBOFLAVIN_MG>
    <NIACIN_MG>.34</NIACIN_MG>
    <VITAMINB6_MG>.06</VITAMINB6_MG>
    <FOLICACID_MCG>6.24</FOLICACID_MCG>
    <VITAMINB12_MCG>.28</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>152.66</PHOSPHOROUS_MG>
    <IODINE_MCG>0</IODINE_MCG>
    <MAGNESIUM_MG>42.34</MAGNESIUM_MG>
    <ZINC_MG>.96</ZINC_MG>
    <SELENIUM_MCG>0</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 2</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Nut and Fruit Mix, Sunflower Kernels and Infused Fruit</ITEM>
    <WEIGHT>56</WEIGHT>
    <CALORIES>314.72</CALORIES>
    <TOTALFAT_G>21.17</TOTALFAT_G>
    <TOTALFAT_DV>.33&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>3.18</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.16&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.03</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>5.6</SODIUM_MG>
    <SODIUM_DV>0&#37;</SODIUM_DV>
    <POTASSIUM_MG>339.92</POTASSIUM_MG>
    <CARBOHYDRATES_G>18.42</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.06&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>10.58</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.42&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>12.6</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.56</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>43.12</CALCIUM_MG>
    <CALCIUM_DV>.04&#37;</CALCIUM_DV>
    <IRON_MG>1.07</IRON_MG>
    <IRON_DV>.06&#37;</IRON_DV>
    <VITAMINE_MG>3.65</VITAMINE_MG>
    <THIAMIN_MG>.08</THIAMIN_MG>
    <RIBOFLAVIN_MG>.09</RIBOFLAVIN_MG>
    <NIACIN_MG>5.88</NIACIN_MG>
    <VITAMINB6_MG>.31</VITAMINB6_MG>
    <FOLICACID_MCG>47.66</FOLICACID_MCG>
    <VITAMINB12_MCG>.07</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>190.96</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>91.84</MAGNESIUM_MG>
    <ZINC_MG>1.57</ZINC_MG>
    <SELENIUM_MCG>4.65</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>MCW/LRP2008</RATION>
    <MENU>MENU 2</MENU>
    <ITEMTYPE>Candy</ITEMTYPE>
    <ITEM>Starch Jelly</ITEM>
    <WEIGHT>57</WEIGHT>
    <CALORIES>190</CALORIES>
    <TOTALFAT_G>.05</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>17</SODIUM_MG>